<?php

/*
 * NuraWeb - Free and Open Source Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 *
 * LICENSE:
 * NuraWeb is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2024, Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@nurasoftware.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Console\Commands;

use Illuminate\Console\Command;

use App\Models\ThemeMenu;
use App\Models\ThemeMenuLang;
use App\Models\ThemeButton;
use App\Models\Config;
use App\Models\Page;
use App\Models\PageContent;
use App\Models\Language;
use Artisan;

class Install extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:install';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Allows to update install directly through CLI';

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        // Migrate tables
        Artisan::call("migrate --path=/database/migrations");
        $this->info('Tables installed!');

        // Add default language (english)
        if (Language::where('is_default', 1)->doesntExist()) {
            $lang = Language::create([
                'name' => 'English',
                'code' => 'en',
                'locale' => 'en_US',
                'status' => 'active',
                'timezone' => 'Europe/London',
                'dir' => 'ltr',
                'site_label' => 'NuraWeb Website',
                'is_default' => 1,
            ]);
            $this->info('Default language added');
        }

        // Get default language
        $default_lang = Language::get_default_language();

        // Add default pages (home page page)
        if (Page::where('is_homepage', 1)->doesntExist()) {
            $page = Page::create([
                'title' => 'Home',
                'meta_title' => 'Home',
                'meta_description' => 'Homepage',
                'parent_id' => null,
                'user_id' => null,
                'active' => 1,
                'blocks' => null,
                'is_homepage' => 1,
            ]);

            PageContent::create([
                'page_id' => $page->id,
                'lang_id' => $default_lang->id,
                'title' => 'Home',
            ]);

            $this->info('Homepage added');
        } else $this->info('Homepage exists');

        // Default button
        if (ThemeButton::where('is_default', 1)->doesntExist()) {
            ThemeButton::create([
                'label' => 'Default',
                'bg_color' => '#143059',
                'font_color' => 'white',
                'border_color' => '#143059',
                'bg_color_hover' => '#365a90',
                'font_color_hover' => 'white',
                'border_color_hover' => '#365a90',
                'shadow' => null,
                'rounded' => 'rounded-1',
                'font_weight' => 'fst-normal',
                'size' => null,
                'is_default' => 1
            ]);
            $this->info('Default button added');
        } else $this->info('Default button exists');

        // Add Home link in menu
        if (ThemeMenu::where('type', 'home')->doesntExist()) {
            $menu_link = ThemeMenu::create([
                'type' => 'home',
                'parent_id' => null,
                'value' => null,
                'position' => 1,
                'new_tab' => 0,
                'btn_id' => null,
                'icon' => null,
            ]);

            ThemeMenuLang::create(
                [
                    'link_id' => $menu_link->id,
                    'lang_id' => $default_lang->id,
                    'label' => 'Home',
                ]
            );

            ThemeMenu::generate_menu_links();
            $this->info('Homepage added in navigation menu');
        } else $this->info('Homepage exists in navigation menu');


        // Website is in maintenance mode by default        
        Config::update_config('website_maintenance_enabled', 'on');
        Config::update_config('website_maintenance_text', '<h1>Website under construction</h1>
        Powered by <a href="https://nuraweb.com">NuraWeb</a> - Free and Open Source Website Builder
        <hr>
        <small class="text-muted">If you are the owner of this website, go to administrator area and start building your awesome website.</small>');

        $this->info('Website maintenance mode OK');

        $this->info('WEBSITE INSTALLED.');
    }
}
