<?php

/*
 * NuraWeb - Free and Open Source Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 *
 * LICENSE:
 * NuraWeb is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2024, Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@nurasoftware.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\BlockController as BlockController;
use App\Http\Controllers\Admin\ConfigController as ConfigController;
use App\Http\Controllers\Admin\ContactController as ContactController;
use App\Http\Controllers\Admin\LangController as LangController;
use App\Http\Controllers\Admin\PageController as PageController;
use App\Http\Controllers\Admin\ProfileController as ProfileController;
use App\Http\Controllers\Admin\ThemeController as ThemeController;
use App\Http\Controllers\Admin\ThemeFooterController as ThemeFooterController;
use App\Http\Controllers\Admin\ThemeButtonController as ThemeButtonController;
use App\Http\Controllers\Admin\ThemeStyleController as ThemeStyleController;
use App\Http\Controllers\Admin\ThemeMenuController as ThemeMenuController;
use App\Http\Controllers\Admin\TranslateController as TranslateController;
use App\Http\Controllers\Admin\RecycleBinController as RecycleBinController;
use App\Http\Controllers\Admin\ToolsController as ToolsController;
use App\Http\Controllers\Admin\UserController as UserController;

Route::get('account/admin', [ToolsController::class, 'dashboard'])->name('admin');

Route::prefix('account/admin')->name('admin.')->group(function () {
    // Dashboard
    Route::get('dashboard', [ToolsController::class, 'dashboard'])->name('dashboard');

    // Accounts
    Route::get('accounts/permissions', [UserController::class, 'permissions'])->name('accounts.permissions');
    Route::post('accounts/permissions', [UserController::class, 'update_permissions']);
    Route::resource('accounts', UserController::class)->parameters(['accounts' => 'id']);

    // Pages
    Route::resource('pages', PageController::class)->parameters(['pages' => 'id']);
    Route::get('pages/{id}/content', [PageController::class, 'content'])->name('pages.content')->where('id', '[0-9]+');
    Route::post('pages/{id}/content', [PageController::class, 'content_update'])->name('pages.content.new')->where('id', '[0-9]+');
    Route::delete('pages/{id}/content/delete/{block_id}', [PageController::class, 'content_destroy'])->name('pages.content.delete')->where('id', '[0-9]+')->where('block_id', '[0-9]+');
    Route::post('pages/{id}/sortable', [PageController::class, 'sortable'])->name('pages.sortable')->where('id', '[0-9]+');
    Route::post('pages/{id}/ajaxPublishSwitch', [PageController::class, 'ajaxPublishSwitch'])->name('pages.ajaxPublishSwitch')->where('id', '[0-9]+');

    // Profile
    Route::get('profile', [ProfileController::class, 'index'])->name('profile');
    Route::post('profile', [ProfileController::class, 'update']);
    Route::delete('profile/delete-avatar', [ProfileController::class, 'delete_avatar'])->name('profile.delete_avatar');

    // Tools
    Route::get('tools', [ToolsController::class, 'tools'])->name('tools');
    Route::post('tools', [ToolsController::class, 'tools_action']);

    // Contact page and contact form
    Route::get('contact/config', [ContactController::class, 'config'])->name('contact.config');
    Route::put('contact/config', [ContactController::class, 'update_config']);

    Route::get('contact/fields', [ContactController::class, 'fields'])->name('contact.fields');
    Route::post('contact/fields/add-field', [ContactController::class, 'add_field'])->name('contact.add_field');
    Route::get('contact/fields/update-field/{field_id}', [ContactController::class, 'show_field'])->name('contact.show_field')->where('field_id', '[0-9]+');
    Route::put('contact/fields/update-field/{field_id}', [ContactController::class, 'update_field'])->name('contact.update_field')->where('field_id', '[0-9]+');
    Route::delete('contact/fields/delete-field/{field_id}', [ContactController::class, 'destroy_field'])->name('contact.delete_field')->where('field_id', '[0-9]+');
    Route::post('contact/fields/sortable-fields', [ContactController::class, 'sortable_fields'])->name('contact.sortable_fields');

    Route::get('contact', [ContactController::class, 'index'])->name('contact');
    Route::get('contact/{id}', [ContactController::class, 'show'])->name('contact.show')->where('id', '[0-9]+');
    Route::get('contact/{id}/to_trash', [ContactController::class, 'to_trash'])->name('contact.to_trash')->where('id', '[0-9]+');
    Route::get('contact/{id}/mark', [ContactController::class, 'mark'])->name('contact.mark')->where('id', '[0-9]+');
    Route::post('contact/multiple-action', [ContactController::class, 'multiple_action'])->name('contact.multiple_action');
    Route::delete('contact/{id}/delete', [ContactController::class, 'to_trash'])->name('contact.delete')->where('id', '[0-9]+');

    // Languages
    Route::resource('languages', LangController::class)->parameters(['languages' => 'id']);

    // Translates routes        
    Route::get('translates', [TranslateController::class, 'index'])->name('translates');
    Route::get('translate-lang', [TranslateController::class, 'translate_lang'])->name('translate_lang');
    Route::post('translates/create_key', [TranslateController::class, 'create_key'])->name('translates.create_key');
    Route::post('translates/update_key', [TranslateController::class, 'update_key'])->name('translates.update_key');
    Route::post('translates/delete_key', [TranslateController::class, 'delete_key'])->name('translates.delete_key');
    Route::post('translates/update_translate', [TranslateController::class, 'update_translate'])->name('translates.update_translate');
    Route::get('translates/regenerate_lang_file', [TranslateController::class, 'regenerate_lang_file'])->name('translates.regenerate_lang_file');
    Route::post('translates/scan_template', [TranslateController::class, 'scan_template'])->name('translates.scan_template');

    // Theme    
    Route::get('theme', [ThemeController::class, 'index'])->name('theme');

    Route::get('theme/logo', [ThemeController::class, 'logo'])->name('theme.logo');
    Route::post('theme/logo', [ThemeController::class, 'update_logo']);

    Route::get('theme/custom-code', [ThemeController::class, 'custom_code'])->name('theme.custom_code');
    Route::post('theme/custom-code',  [ThemeController::class, 'update_custom_code']);

    Route::get('theme/menu/dropdown', [ThemeMenuController::class, 'index_dropdowns'])->name('theme.menu.dropdown');
    Route::post('theme/menu/dropdown', [ThemeMenuController::class, 'store_dropdown']);
    Route::put('theme/menu/dropdown', [ThemeMenuController::class, 'update_dropdown']);
    Route::delete('theme/menu/dropdown', [ThemeMenuController::class, 'destroy_dropdown']);
    Route::post('theme/menu/sortable-dropdowns/{parent_link_id}', [ThemeMenuController::class, 'sortable_dropdowns'])->name('theme.menu.sortable_dropdowns')->where('parent_link_id', '[0-9]+');
    Route::resource('theme/menu', ThemeMenuController::class)->names(['index' => 'theme.menu', 'create' => 'theme.menu.create', 'show' => 'theme.menu.show'])->parameters(['menu' => 'id']);
    Route::post('theme/menu/sortable', [ThemeMenuController::class, 'sortable'])->name('theme.menu.sortable');

    // Theme footer content routes
    Route::get('theme/footer', [ThemeFooterController::class, 'index'])->name('theme.footer');
    Route::put('theme/footer', [ThemeFooterController::class, 'update']);

    Route::get('theme/footer/{footer}/content', [ThemeFooterController::class, 'content'])->name('theme.footer.content')->where(['footer' => '[a-z0-9_-]+']);

    Route::post('theme/footer/{footer}/content', [ThemeFooterController::class, 'update_content'])->where(['footer' => '[a-z0-9_-]+']);

    Route::post('theme/footer/{footer}/{col}/sortable', [ThemeFooterController::class, 'sortable'])->name('theme.footer.sortable')->where('footer', '[a-z0-9_-]+')->where('col', '[0-9]+');
    Route::delete('theme/footer/delete/{block_id}', [ThemeFooterController::class, 'delete_content'])->name('theme.footer.content.delete')->where('block_id', '[0-9]+');
    Route::get('theme/footer/block/{id}', [ThemeFooterController::class, 'block'])->name('theme.footer.block')->where('id', '[0-9]+');
    Route::put('theme/footer/block/{id}', [ThemeFooterController::class, 'block_update'])->where('id', '[0-9]+');

    // Buttons
    Route::resource('theme/buttons', ThemeButtonController::class)->names(['index' => 'theme.buttons.index', 'create' => 'theme.buttons.create', 'show' => 'theme.buttons.show'])->parameters(['buttons' => 'id']);

    // Styles
    Route::get('theme/styles', [ThemeStyleController::class, 'index'])->name('theme.styles.index');
    Route::get('theme/styles/{style}', [ThemeStyleController::class, 'show'])->name('theme.styles.show')->where('style', '[0-9a-zA-Z_-]+');
    Route::put('theme/styles/{style}', [ThemeStyleController::class, 'update'])->where('style', '[0-9a-zA-Z_-]+');

    Route::post('theme/styles', [ThemeStyleController::class, 'store_custom']);
    Route::get('theme/custom-styles/{id}', [ThemeStyleController::class, 'show_custom'])->name('theme.custom_styles.show')->where('id', '[0-9]+');
    Route::put('theme/custom-styles/{id}', [ThemeStyleController::class, 'update_custom'])->where('id', '[0-9a-zA-Z_-]+');
    Route::delete('theme/custom-styles/{id}', [ThemeStyleController::class, 'destroy_custom'])->where('id', '[0-9]+');

    // Config
    Route::get('/config/{module}', [ConfigController::class, 'module'])->name('config')->where(['module' => '[a-z0-9_-]+']);
    Route::post('/config/{module}', [ConfigController::class, 'update_module'])->where(['module' => '[a-z0-9_-]+']);

    // Blocks routes
    Route::resource('blocks', BlockController::class)->parameters(['blocks' => 'id']);

    // Recycle Bin
    Route::get('recycle-bin', [RecycleBinController::class, 'index'])->name('recycle_bin');
    Route::get('recycle-bin/empty/{module}', [RecycleBinController::class, 'empty'])->name('recycle_bin.empty')->where('module', '[a-zA-Z0-9]+');
    Route::post('recycle-bin/multiple-action/{module}', [RecycleBinController::class, 'multiple_action'])->name('recycle_bin.multiple_action')->where('module', '[a-zA-Z0-9]+');
    Route::get('recycle-bin/single-action/{module}/{id}', [RecycleBinController::class, 'single_action'])->name('recycle_bin.single_action')->where('module', '[a-zA-Z0-9]+')->where('id', '[0-9]+');
    Route::get('recycle-bin/{module}', [RecycleBinController::class, 'module'])->name('recycle_bin.module')->where('module', '[a-zA-Z0-9]+');

    // Other routes
    Route::get('ajax/{source}', [ToolsController::class, 'ajax_fetch'])->name('ajax')->where('source', '[a-z0-9_-]+');
    Route::get('preview-style/{id}', [ToolsController::class, 'preview_style'])->name('preview-style')->where('id', '[a-z0-9_-]+');
    Route::get('tools/generate-sitemap', [ToolsController::class, 'generate_sitemap'])->name('sitemap.generate');
});
