<?php

/*
 * NuraWeb - Free and Open Source Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 *
 * LICENSE:
 * NuraWeb is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2024, Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@nurasoftware.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */

use Illuminate\Support\Facades\Route;
use App\Models\Language;
use App\Http\Controllers\Web\HomeController as WebHomeController;
use App\Http\Controllers\Web\PageController as WebPageController;
use App\Http\Controllers\Web\ContactController as WebContactController;
use App\Http\Controllers\Web\ToolsController as WebToolsController;

Route::get('/account', function () {
    if (Auth::user()) {
        if (Auth::user()->role == 'admin' || Auth::user()->role == 'internal') return redirect(route('admin'));
    } else return redirect(route('login'));
})->name('account');


// Maintenance
Route::get('/maintenance-mode', [WebToolsController::class, 'maintenance'])->name('maintenance');



foreach (Language::get_active_languages() as $language) {
    if ($language->is_default == 1) {
        // DEFAULT LANGUAGE 

        // Homepage
        Route::get('/', [WebHomeController::class, 'index'])->name('home');

        // Contact page
        Route::get('/contact', [WebContactController::class, 'index'])->name('contact');
        Route::post('contact', [WebContactController::class, 'store']);

        // Static page with parent
        Route::get('{parent_slug}/{slug}', [WebPageController::class, 'show'])->name('child_page')->where(['parent_slug' => '[a-z0-9_-]{3,}+', 'slug' => '[a-z0-9_-]+']); // if page is a child of a parent page

        // Static Page
        Route::get('{slug}', [WebPageController::class, 'show'])->name('page')->where(['slug' => '[a-z0-9_-]{3,}+']);
    } else {
        // OTHER LANGUAGES

        // Homepage
        Route::get("/{$language->code}", [WebHomeController::class, 'index'])->name("home.{$language->code}");

        // Contact page
        Route::get("{$language->code}/contact", [WebContactController::class, 'index'])->name("contact.{$language->code}");
        Route::post("{$language->code}/contact", [WebContactController::class, 'store']);

        // Static page with parent
        Route::get("{$language->code}/{parent_slug}/{slug}", [WebPageController::class, 'show'])->name("child_page.{$language->code}")->where(['parent_slug' => '[a-z0-9_-]{3,}+', 'slug' => '[a-z0-9_-]+']); // if page is a child of a parent page

        // Static Page
        Route::get("{$language->code}/{slug}", [WebPageController::class, 'show'])->name("page.{$language->code}")->where(['slug' => '[a-z0-9_-]{3,}+']);
    }
}
