<?php

/*
 * NuraWeb - Free and Open Source Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 *
 * LICENSE:
 * NuraWeb is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2024, Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@nurasoftware.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Policies;

use App\Models\Contact;
use App\Models\User;
use App\Models\UserPermission;
use Illuminate\Auth\Access\Response;

class ContactPolicy
{
    public function before(User $user, string $ability): bool|null
    {
        if ($user->role == 'admin') return true;

        return null;
    }

    /**
     * Determine whether the user can view any models.
     */
    public function viewAny(User $user): bool
    {
        return UserPermission::checkPermission($user->id, 'Contact', 'viewAny');
    }
    

    /**
     * Determine whether the user can delete the model.
     */
    public function delete(User $user, Contact $message = null): bool
    {
        if (!UserPermission::checkPermission($user->id, 'Contact', 'viewAny')) return false; // viewAny permission is required to delete item

        if (UserPermission::checkPermission($user->id, 'Contact', 'delete')) return true; // check if user has delete permission        
        else return false;

    }
}
