<?php

/*
 * NuraWeb - Free and Open Source Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 *
 * LICENSE:
 * NuraWeb is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2024, Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@nurasoftware.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('theme_buttons', function (Blueprint $table) {
            $table->id();
            $table->string('label', 100);
            $table->string('bg_color', 20)->nullable();
            $table->string('font_color', 20)->nullable();
            $table->string('border_color', 20)->nullable();
            $table->string('bg_color_hover', 20)->nullable();
            $table->string('font_color_hover', 20)->nullable();
            $table->string('border_color_hover', 20)->nullable();
            $table->string('shadow', 20)->nullable();
            $table->string('rounded', 20)->nullable();
            $table->string('font_weight', 20)->nullable();
            $table->string('size', 20)->nullable();
            $table->boolean('is_default', 20)->default(false);            
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('theme_buttons');
    }
};
