<?php

/*
 * NuraWeb - Free and Open Source Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 *
 * LICENSE:
 * NuraWeb is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2024, Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@nurasoftware.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('posts', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('lang_id')->nullable();
            $table->string('title', 250)->index('title');
            $table->string('slug', 250);
            $table->string('url', 250)->nullable();
            $table->string('image', 250)->nullable();
            $table->unsignedBigInteger('user_id')->nullable();
            $table->integer('categ_id')->nullable();
            $table->string('status', 20);
            $table->text('summary')->nullable();
            $table->mediumText('content')->nullable();
            $table->text('tags')->nullable();
            $table->tinyInteger('featured')->nullable();
            $table->string('meta_title', 250)->nullable();
            $table->string('meta_description', 250)->nullable();
            $table->integer('updated_by_user_id')->nullable();
            $table->integer('hits')->default(0);
            $table->smallInteger('minutes_to_read')->nullable();
            $table->text('search_terms')->nullable();
            $table->mediumtext('blocks')->nullable();
            $table->timestamps();
            $table->softDeletes();
            
            $table->foreign('lang_id')->references('id')->on('languages')->onDelete('cascade');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('posts');
    }
};
