<?php

/*
 * NuraWeb - Free and Open Source Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 *
 * LICENSE:
 * NuraWeb is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2024, Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@nurasoftware.com>
 * 
 * 
 * !!!!!! IMPORTANT: 
 * DO NOT edit this file manually. All changes will be lost after software update. 
 * Add your custom configuration in 'config/custom-nura.php' file
 */

return [

    /*
    |--------------------------------------------------------------------------
    | Application Demo Mode
    |--------------------------------------------------------------------------
    |
    | Values: true or false
    | If true, the application is in demo mode and any action related to content (create, update, delete) is disabled.
    |
    */
    'demo_mode' => env('APP_DEMO_MODE', false),


    /*
    |--------------------------------------------------------------------------
    | Content blocks for pages
    |--------------------------------------------------------------------------
    |
    */
    'blocks' => [
        'text' => [
            'label' => 'Simple text',
            'icon' => '<i class="bi bi-file-text"></i>'
        ],
        'editor' => [
            'label' => 'Text Editor / HTML',
            'icon' => '<i class="bi bi-textarea-t"></i>'
        ],
        'image' => [
            'label' => 'Image / Banner',
            'icon' => '<i class="bi bi-image"></i>'
        ],
        'gallery' => [
            'label' => 'Images gallery',
            'icon' => '<i class="bi bi-images"></i>'
        ],
        'video' => [
            'label' => 'Video',
            'icon' => '<i class="bi bi-play-btn"></i>'
        ],
        'card' => [
            'label' => 'Cards',
            'icon' => '<i class="bi bi-file-richtext"></i>'
        ],
        'hero' => [
            'label' => 'Hero',
            'icon' => '<i class="bi bi-card-heading"></i>'
        ],
        'slider' => [
            'label' => 'Slider',
            'icon' => '<i class="bi bi-collection"></i>'
        ],
        'custom' => [
            'label' => 'Custom',
            'icon' => '<i class="bi bi-code"></i>'
        ],

        'accordion' => [
            'label' => 'Accordion',
            'icon' => '<i class="bi bi-menu-up"></i>'
        ],
        'alert' => [
            'label' => 'Alert',
            'icon' => '<i class="bi bi-exclamation-square"></i>'
        ],
        'map' => [
            'label' => 'Google Map',
            'icon' => '<i class="bi bi-geo-alt"></i>'
        ],
        'blockquote' => [
            'label' => 'Blockquote',
            'icon' => '<i class="bi bi-chat-left-quote"></i>'
        ],
        'testimonial' => [
            'label' => 'Testimonial',
            'icon' => '<i class="bi bi-star-half"></i>'
        ],
    ],


    /*
    |--------------------------------------------------------------------------
    | Content blocks for footer
    |--------------------------------------------------------------------------
    |
    */
    'footer_blocks' => [
        'text' => [
            'label' => 'Simple text',
            'icon' => '<i class="bi bi-file-text"></i>'
        ],
        'editor' => [
            'label' => 'Text Editor / HTML',
            'icon' => '<i class="bi bi-textarea-t"></i>'
        ],
        'image' => [
            'label' => 'Image / Banner',
            'icon' => '<i class="bi bi-image"></i>'
        ],
        'links' => [
            'label' => 'Links',
            'icon' => '<i class="bi bi-list-ul"></i>'
        ],
        'custom' => [
            'label' => 'Custom',
            'icon' => '<i class="bi bi-code"></i>'
        ],
    ],



    /*
    |--------------------------------------------------------------------------
    | Content blocks for posts (blog)
    |--------------------------------------------------------------------------
    |
    */
    'posts_blocks' => [
        'text' => [
            'label' => 'Simple text',
            'icon' => '<i class="bi bi-file-text"></i>'
        ],
        'editor' => [
            'label' => 'Text Editor / HTML',
            'icon' => '<i class="bi bi-textarea-t"></i>'
        ],
        'image' => [
            'label' => 'Image / Banner',
            'icon' => '<i class="bi bi-image"></i>'
        ],
        'gallery' => [
            'label' => 'Images gallery',
            'icon' => '<i class="bi bi-images"></i>'
        ],
        'video' => [
            'label' => 'Video',
            'icon' => '<i class="bi bi-play-btn"></i>'
        ],
        'custom' => [
            'label' => 'Custom',
            'icon' => '<i class="bi bi-code"></i>'
        ],
        'accordion' => [
            'label' => 'Accordion',
            'icon' => '<i class="bi bi-menu-up"></i>'
        ],
        'alert' => [
            'label' => 'Alert',
            'icon' => '<i class="bi bi-exclamation-square"></i>'
        ],
        'blockquote' => [
            'label' => 'Blockquote',
            'icon' => '<i class="bi bi-chat-left-quote"></i>'
        ],        
    ],



    'defaults' => [
        // Global defaults
        "font_family" => "'Open Sans', sans-serif",
        "intro_text" => "Welcome.",
        "font_size" => "1em",
        "font_color" => "#3E3E3E",
        "font_color_light" => "#b9b9b9",

        "h1_size" => "2em",
        "h2_size" => "1.5em",
        "h3_size" => "1.2em",
        "h4_size" => "1.1em",
        "title_size" => "1.3em",

        "bg_color_dark" => "#5F5F5F",
        "bg_color" => "#FFFFFF",

        "link_color" => "#1A94FF",
        "link_color_hover" => "#006DCD",
        "link_color_underline" => "#3E3E3E",
        "link_color_underline_hover" => "#006DCD",
        "link_decoration" => "none",
        "link_hover_decoration" => "underline",

        "nav_bg_color" => "#334E5C",
        "nav_font_color" => "#DADADA",
        "nav_font_size" => "1em",
        "nav_link_color" => "#F0F0F0",
        "nav_link_color_hover" => "#D8E3E9",
        "nav_link_color_underline" => "#D8E3E9",
        "nav_link_hover_decoration" => "none",

        "dropdown_font_color" => "#3e3e3e",
        "dropdown_bg_color" => "#fbf7f0",
        "dropdown_link_color" => "#cd2653",
        "dropdown_link_color_hover" => "#d7446b",
        "dropdown_link_color_underline" => "#5d5d5d",
        "dropdown_bg_color_hover" => "#d7446b",
        "dropdown_link_hover_decoration" => "none",

        "button_font_color" => "#FFFFFF",
        "button_bg_color" => "#40A6FF",
        "button_border_color" => "#40A6FF",
        "button_font_color_nover" => "#f4f7f8",
        "button_bg_color_hover" => "#1A94FF",
        "button_border_color_hover" => "#1A94FF",
    ],
];
