<?php

/*
 * NuraWeb - Free and Open Source Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 *
 * LICENSE:
 * NuraWeb is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2024, Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@nurasoftware.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */

use Illuminate\Http\Request;
use App\Models\DriveFile;
use App\Models\Language;

if (!function_exists('delete_image')) {
	function delete_image($file_code)
	{

		$file = DriveFile::where('code', $file_code)->value('file');

		// delete main image
		$filename = getcwd() . '/uploads/' . $file;
		if (file_exists($filename)) @unlink($filename);

		// delete thumb, if exists
		$pos = strrpos($file, '/');
		if ($pos !== false) {
			$thumb_file = substr_replace($file, '/thumb_', $pos, 1);
			if (file_exists('uploads/' . $thumb_file)) @unlink('uploads/' . $thumb_file);
		}

		// delete thumb square, if exists
		$pos = strrpos($file, '/');
		if ($pos !== false) {
			$thumb_square_file = substr_replace($file, '/thumb_square_', $pos, 1);
			if (file_exists('uploads/' . $thumb_square_file)) @unlink('uploads/' . $thumb_square_file);
		}

		// delete thumb rectangle, if exists
		$pos = strrpos($file, '/');
		if ($pos !== false) {
			$thumb_rectangle_file = substr_replace($file, '/thumb_rectangle_', $pos, 1);
			if (file_exists('uploads/' . $thumb_rectangle_file)) @unlink('uploads/' . $thumb_rectangle_file);
		}

		DriveFile::where('code', $file_code)->delete();

		return;
	}
}



if (!function_exists('delete_file')) {
	function delete_file($file)
	{
		// delete file
		$filename = getcwd() . '/uploads/' . $file;
		if (file_exists($filename))
			@unlink($filename);
		return;
	}
}


if (!function_exists('get_default_language')) {
	function get_default_language()
	{
		$lang = Language::where('is_default', 1)->first();

		return $lang;
	}
}
