<?php

namespace App\Http\Controllers\Web;

/*
 * NuraWeb - Free and Open Source Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 *
 * LICENSE:
 * NuraWeb is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2024, Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@nurasoftware.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Post;
use App\Models\PostCateg;
use App\Models\PostTag;
use App\Models\PostTagItem;
use App\Models\Config;
use App\Models\Language;

class PostController extends Controller
{

    /**
     * All posts
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (((Config::config()->module_posts ?? null) != 'active')) return redirect(route('home'));

        $posts = Post::with('author', 'category')->whereNull('deleted_at')
            ->whereHas('category', function ($query) {
                $query->where('active', 1);
            })
            ->where('lang_id', Language::get_active_language()->id ?? null)
            ->where('status', 'published')
            ->orderByDesc('featured')->orderByDesc('id')->paginate(Config::config()->posts_per_page ?? 12);

        $categories = PostCateg::withCount('posts')->where('active', 1)->where('lang_id', Language::get_active_language()->id)->limit(200)->get();

        // layout
        if (Config::config()->tpl_posts_home_layout_id ?? null) $layout = TemplateLayout::find(Config::config()->tpl_posts_home_layout_id);

        return view('web.posts', [
            'posts' => $posts,
            'categories' => $categories,

            'layout' => $layout ?? null,
            'layout_top' => $layout->top ?? null,
            'layout_bottom' => $layout->bottom ?? null,
            'layout_sidebar' => $layout->sidebar ?? null,
        ]);
    }

    /**
     * Al posts from a category slug
     *
     * @return \Illuminate\Http\Response
     */
    public function categ(Request $request)
    {
        if (((Config::config()->module_posts ?? null) != 'active')) return redirect(route('home'));

        $categ_slug = $request->categ_slug;

        $categ = PostCateg::where('slug', $categ_slug)->where('active', 1)->where('lang_id', Language::get_active_language()->id)->first();
        if (!$categ) return redirect(route('posts'));

        $categ_tree_ids = $categ->tree_ids ?? null;
        if ($categ_tree_ids) $categ_tree_ids_array = explode(',', $categ_tree_ids);

        $posts = Post::with('author', 'category')->whereNull('deleted_at')
            ->whereHas('category', function ($query) {
                $query->where('active', 1);
            })
            ->where('status', 'published')
            ->whereIn('posts.categ_id', $categ_tree_ids_array)
            ->orderByDesc('featured')
            ->orderByDesc('posts.id')
            ->paginate(Config::config()->posts_per_page ?? 12);

        // layout
        if (Config::config()->tpl_posts_categ_layout_id ?? null) $layout = TemplateLayout::find(Config::config()->tpl_posts_categ_layout_id);

        return view('web.posts-categ', [
            'posts' => $posts,
            'categ' => $categ,

            'layout' => $layout ?? null,
            'layout_top' => $layout->top ?? null,
            'layout_bottom' => $layout->bottom ?? null,
            'layout_sidebar' => $layout->sidebar ?? null,
        ]);
    }


    /**
     *  Show item
     */
    public function show(Request $request)
    {
        if (((Config::config()->module_posts ?? null) != 'active')) return redirect(route('home'));

        $slug = $request->slug;
        $categ_slug = $request->categ_slug;

        if (!$slug || !$categ_slug) return redirect(route('posts'));

        $post = Post::with('author', 'category')->whereNull('deleted_at')
            ->whereHas('category', function ($query) use ($categ_slug) {
                $query->where('active', 1)->where('lang_id', Language::get_active_language()->id)->where('slug', $categ_slug);
            })
            ->where('status', 'published')
            ->where('slug', $slug)
            ->where('lang_id', Language::get_active_language()->id)
            ->first();

        if (!$post) return redirect(route('posts'));

        if ($post->blocks) $content_blocks = unserialize($post->blocks);

        $categ = PostCateg::where('id', $post->categ_id)->where('active', 1)->first();
        if (!$categ) return redirect(route('posts'));

        $tags = PostTagItem::with('tag')->where('post_id', $post->id)->get();

        $related_posts = Post::where('id', '!=', $post->id)
            ->whereNull('deleted_at')
            ->where('status', 'published')
            ->orderByDesc('featured')
            ->orderByDesc('id')
            ->where('categ_id', $post->categ_id)
            ->where('lang_id', Language::get_active_language()->id)
            ->limit(Config::config()->posts_per_page ?? 12)
            ->get();

        // update hits
        Post::where('id', $post->id)->increment('hits');
        
        return view('web.post', [
            'post' => $post,
            'content_blocks' => $content_blocks ?? array(),
            'related_posts' => $related_posts,
            'tags' => $tags,
        ]);
    }


    /**
     * Search results
     */
    public function search(Request $request)
    {
        if (((Config::config()->module_posts ?? null) != 'active')) return redirect(route('home'));

        $s = $request->s;
        $lang = $request->lang;

        $posts = Post::with('author', 'category')
            ->whereNull('deleted_at')
            ->where('status', 'published')
            ->where(function ($query) use ($s) {
                $query->where('title', 'like', "%$s%")
                    ->orWhere('search_terms', 'like', "%$s%")
                    ->orWhere('tags', 'like', "%$s%");
            });

        if (!$lang) {
            $posts = $posts->where('posts.lang_id', Language::get_default_language()->id);
        } else {
            $posts = $posts->where('posts.lang_id', Language::get_active_language()->id);
        }

        $posts = $posts->orderBy('posts.featured', 'desc')
            ->orderBy('posts.id', 'desc')
            ->paginate(Config::config()->posts_per_page ?? 12);

        return view('web.posts-search', [
            'posts' => $posts,
            's' => $s,
        ]);
    }


    /**
     * Al posts from a tag slug
     *
     * @return \Illuminate\Http\Response
     */
    public function tag(Request $request)
    {
        if (((Config::config()->module_posts ?? null) != 'active')) return redirect(route('home'));

        $slug = $request->slug;

        $tag = PostTag::where('slug', $slug)->where('lang_id', Language::get_active_language()->id)->first();
        if (!$tag) return redirect(route('posts'));

        $posts = PostTagItem::with('post')
            ->whereHas('post', function ($query) {
                $query->where('status', 'published')->whereNull('deleted_at');
            })
            ->where('tag_id', $tag->id)
            ->where('lang_id', Language::get_active_language()->id)
            ->paginate(Config::config()->posts_per_page ?? 12);

        return view('web.posts-tag', [
            'tag' => $tag,
            'posts' => $posts,
        ]);
    }
}
