<?php

namespace App\Models;

/*
 * NuraWeb - Free and Open Source Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 *
 * LICENSE:
 * NuraWeb is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2024, Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <contact@nurasoftware.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */


use Illuminate\Database\Eloquent\Model;

class PostTagItem extends Model
{

    protected $fillable = [
        'tag_id',
        'post_id',
        'lang_id',
    ];

    protected $table = 'post_tag_items';

    public $timestamps = false;

    public function tag()
    {
        return $this->belongsTo(PostTag::class, 'tag_id');
    }

    public function post()
    {
        return $this->belongsTo(Post::class, 'post_id')->with('author')->where('status', 'published');
    }


    public static function recountTagItems($lang_id)
    {
        $tags = PostTag::where('lang_id', $lang_id)->get();

        foreach ($tags as $tag) {
            // count articles with this tag
            $count_posts = PostTagItem::where('tag_id', $tag->id)->where('lang_id', $lang_id)->count();
            PostTag::where('id', $tag->id)->update(['counter' => $count_posts]);
        }

        return;
    }
}
