<?php

/*
 * NuraWeb - Free and Open Source Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 *
 * LICENSE:
 * NuraWeb is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2024, Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@nurasoftware.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ThemeStyle extends Model
{
    protected $fillable = [
        'label',
        'text_color',
        'text_size',
        'text_align',
        'title_size',
        'subtitle_size',
        'title_font_weight',
        'subtitle_font_weight',
        'text_font_weight',
        'link_font_weight',
        'link_color',
        'link_hover_color',
        'link_underline_color',
        'link_underline_color_hover',
        'link_decoration',
        'link_hover_decoration',
        'link_underline_tickness',
        'link_underline_offset',
        'font_family',
        'font_family_weights',
        'bg_color',
    ];

    protected $table = 'theme_styles';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;
}
