<?php

/*
 * NuraWeb - Free and Open Source Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 *
 * LICENSE:
 * NuraWeb is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2024, Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@nurasoftware.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;
use Auth;
use App\Models\Page;
use App\Models\PageContent;
use App\Models\Tools;
use App\Models\ThemeMenu;
use App\Models\Block;
use App\Models\Language;

class PageController extends Controller
{

    public function __construct()
    {
        $this->root_pages = Page::with('content')->where('is_homepage', 0)->whereNull('parent_id')->whereNull('deleted_at')->orderByDesc('active')->get();
        $this->langs = Language::get_languages(); // active and inactive languages
    }


    /**
     * Display all resources
     */
    public function index(Request $request)
    {
        // check if user can view items
        if ($request->user()->cannot('view', Page::class)) return redirect(route('admin'))->withErrors('Forbidden');

        $search_terms = $request->search_terms;

        $pages = Page::with('author', 'parent', 'translations')
            ->whereNull('deleted_at')
            ->orderByDesc('is_homepage')
            ->orderByDesc('active')
            ->orderByDesc('id');

        if ($search_terms) {
            $pages = Page::whereHas('translations', function ($query) use ($search_terms) {
                $query->where('title', 'like', "%$search_terms%");
            });
        }

        // check if user can view own items only
        if (!$request->user()->can('viewAny', Page::class)) $pages = $pages->where('user_id', $request->user()->id);

        $pages = $pages->paginate(25);

        $count_draft = Page::where('active', 0)->count();

        return view('admin.index', [
            'view_file' => 'pages.index',
            'active_menu' => 'pages',
            'search_terms' => $search_terms,
            'pages' => $pages,
            'count_draft' => $count_draft,
        ]);
    }


    /**
     * Show form to add new resource
     */
    public function create(Request $request)
    {
        if ($request->user()->cannot('create', Page::class)) return redirect(route('admin.pages.index'))->withErrors('Forbidden');

        return view('admin.index', [
            'view_file' => 'pages.create',
            'active_menu' => 'pages',
            'root_pages' => $this->root_pages,
        ]);
    }


    /**
     * Create new page
     */
    public function store(Request $request)
    {
        if ($request->user()->cannot('create', Page::class)) return redirect(route('admin.pages.index'))->withErrors('Forbidden');

        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        if ($request->slug) $slug = Str::slug($request->slug, '-');
        else $slug = Str::slug($request->title, '-');

        $page = Page::create([
            'parent_id' => $request->parent_id,
            'user_id' => Auth::user()->id,
            'active' => 0,
        ]);

        foreach ($this->langs as $lang) {
            $title = $request['title_' . $lang->id];
            $meta_title = $request['meta_title_' . $lang->id];
            $meta_description = $request['meta_description_' . $lang->id];
            $slug = $request['slug_' . $lang->id];

            if ($slug) $slug = Str::slug($request['slug_' . $lang->id], '-');
            else $slug = Str::slug($request['title_' . $lang->id], '-');

            if (PageContent::where('slug', $slug)->where('lang_id', $lang->id)->exists()) {
                $slug =  $slug . "-" . $page->id;
            }

            // 2 characters is for language only
            if (strlen($slug) == 2) return redirect(route('admin.pages.create'))->with('error', 'length2');

            if ($title) {
                PageContent::create(['page_id' => $page->id, 'lang_id' => $lang->id, 'title' => $title, 'meta_title' => $meta_title, 'meta_description' => $meta_description, 'slug' => $slug]);
            }
        }

        Tools::generateSitemap();

        return redirect(route('admin.pages.content', ['id' => $page->id]))->with('success', 'created');
    }


    /**
     * Show form to edit resource     
     */
    public function show(Request $request)
    {
        $page = Page::where('id', $request->id);

        // check if user can view own posts only
        if (!$request->user()->can('viewAny', Page::class)) $page = $page->where('user_id', $request->user()->id);

        $page = $page->first();

        if (!$page) return redirect(route('admin.pages.index'));
        if ($page->deleted_at && Auth::user()->role != 'admin') return redirect(route('admin.pages.index'));

        if ($request->user()->cannot('view', $page)) return redirect(route('admin.pages.index'))->withErrors('Forbidden');

        // Retrieve page content for each language.
        $contents = Language::where('status', '!=', 'disabled')->with(['page_content' => function ($query) use ($request) {
            $query->where('page_id', $request->id);
        }])->orderByDesc('is_default')->get();

        return view('admin.index', [
            'view_file' => 'pages.update',
            'active_menu' => 'pages',
            'nav_menu' => 'details',
            'page' => $page,
            'contents' => $contents,
            'root_pages' => $this->root_pages,
        ]);
    }


    /**
     * Update the specified resource     
     */
    public function update(Request $request)
    {

        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        $page = Page::find($request->id);
        if (!$page) return redirect(route('admin.pages.index'));

        if ($request->user()->cannot('update', $page)) return redirect(route('admin.pages.index'))->withErrors('Forbidden');

        Page::where('id', $request->id)->update([
            'parent_id' => $request->parent_id ?? null,
            'active' => $request->has('active') ? 1 : 0,
        ]);


        foreach ($this->langs as $lang) {
            $title = $request['title_' . $lang->id];
            $meta_title = $request['meta_title_' . $lang->id];
            $meta_description = $request['meta_description_' . $lang->id];
            $slug = $request['slug_' . $lang->id];

            if ($page->is_homepage == 1) {
                PageContent::updateOrCreate(
                    ['page_id' => $request->id, 'lang_id' => $lang->id],
                    ['meta_title' => $meta_title, 'meta_description' => $meta_description]
                );
            } else {
                if ($title) {
                    if ($slug) $slug = Str::slug($request['slug_' . $lang->id], '-');
                    else $slug = Str::slug($request['title_' . $lang->id], '-');

                    if (PageContent::where('slug', $slug)->where('lang_id', $lang->id)->where('page_id', '!=', $request->id)->exists())  $slug =  $slug . "-" . $request->id;

                    // 2 characters is for language only
                    if (strlen($slug) == 2) return redirect(route('admin.pages.show', ['id' => $request->id]))->with('error', 'length2');

                    PageContent::updateOrCreate(
                        ['page_id' => $request->id, 'lang_id' => $lang->id],
                        ['title' => $title, 'meta_title' => $meta_title, 'meta_description' => $meta_description, 'slug' => $slug]
                    );
                }
            }

            // for sub-pages
            $subpages = Page::where('parent_id', $page->id)->get();
            foreach ($subpages as $subpage) {
                PageContent::where('page_id', $subpage->id)->where('lang_id', $lang->id)->update(['lang_id' => $lang->id]);
            }
        }

        // regenerate menu links for each language and store in cache config
        ThemeMenu::generate_menu_links();
        Tools::generateSitemap();

        if ($request->redirect == 'return')
            return redirect(route('admin.pages.show', ['id' => $request->id]))->with('success', 'updated');
        elseif ($request->redirect == 'content')
            return redirect(route('admin.pages.content', ['id' => $request->id]))->with('success', 'updated');
        else
            return redirect(route('admin.pages.index'))->with('success', 'updated');
    }



    /**
     * Remove the specified resource
     */
    public function destroy(Request $request)
    {

        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        $page = Page::find($request->id);
        if (!$page) return redirect(route('admin.pages.index'));

        if ($request->user()->cannot('delete', $page)) return redirect(route('admin.pages.index'))->withErrors('Forbidden');

        Page::where('parent_id', $request->id)->update(['deleted_at' => now()]);
        Page::where('id', $request->id)->update(['deleted_at' => now()]);

        /*
        // delete content blocks
        $blocks = Block::where('module', 'pages')->where('content_id', $request->id)->get();
        foreach ($blocks as $block) {
            Block::where('id', $block->id)->delete();
            BlockContent::where('block_id', $block->id)->delete();
        }

        Page::where('parent_id', $request->id)->update(['parent_id' => null]);
        TemplateMenu::where('type', 'page')->where('value', $request->id)->delete();
        Page::where('id', $request->id)->delete();
        PageContent::where('page_id', $request->id)->delete();

        // regenerate menu links for each language and store in cache config
        TemplateMenu::generate_menu_links();
        */

        Tools::generateSitemap();

        return redirect(route('admin.pages.index'))->with('success', 'deleted');
    }



    /**
     * Show form to edit content     
     */
    public function content(Request $request)
    {
        // Retrieve page content
        $page = Page::find($request->id);
        if (!$page) return redirect(route('admin.pages.index'));

        if ($request->user()->cannot('view', $page)) return redirect(route('admin.pages.index'))->withErrors('Forbidden');

        return view('admin.index', [
            'view_file' => 'pages.content',
            'active_menu' => 'pages',
            'nav_menu' => 'content',
            'page' => $page,
            'module' => 'pages',
        ]);
    }



    /**
     * Update page content   
     */

    public function content_update(Request $request)
    {

        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        $page = Page::find($request->id);
        if (!$page) return redirect(route('admin.pages.index'));

        if ($request->user()->cannot('update', $page)) return redirect(route('admin.pages.index'))->withErrors('Forbidden');

        if (!$request->type) return redirect(route('admin.pages.content', ['id' => $request->id]));

        $last_pos = Block::where('module', 'pages')->where('content_id', $request->id)->orderByDesc('position')->value('position');
        $position = ($last_pos ?? 0) + 1;

        $block = Block::create([
            'type' => $request->type,
            'module' => 'pages',
            'label' => $request->label ?? null,
            'content_id' => $page->id,
            'position' => $position,
            'created_by_user_id' =>  Auth::user()->id
        ]);

        Block::regenerate_content_blocks('pages', $request->id);

        return redirect(route('admin.blocks.show', ['id' => $block->id]));
    }



    /**
     * Remove the specified block content
     */
    public function content_destroy(Request $request)
    {

        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        $page = Page::find($request->id);
        if (!$page) return redirect(route('admin.pages.index'));

        if ($request->user()->cannot('update', $page)) return redirect(route('admin.pages.index'))->withErrors('Forbidden');

        Block::where('id', $request->block_id)->delete();

        // regenerate content blocks and add blocks in module table (for database performance)
        Block::regenerate_content_blocks('pages', $request->id);

        return redirect(route('admin.pages.content', ['id' => $request->id]))->with('success', 'deleted');
    }


    /**
     * Ajax sortable
     */
    public function sortable(Request $request)
    {
        if ($request->user()->cannot('update', Page::class)) return;

        $i = 0;
        $records = $request->all();

        foreach ($records['item'] as $key => $value) {

            Block::where('module', 'pages')
                ->where('content_id', $request->id)
                ->where('id', $value)
                ->update([
                    'position' => $i,
                ]);

            $i++;
        }

        Block::regenerate_content_blocks('pages', $request->id);
    }


    public function ajaxPublishSwitch(Request $request)
    {
        $page = Page::find($request->id);
        if (!$page) return redirect(route('admin.pages.index'));

        if ($request->user()->cannot('update', $page)) return;

        Page::where('id', $request->id)->update(['active' => 1]);
        return;
    }
}
